enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
cli-source = "revanced/revanced-cli"
build-mode = "module"
riplib = false

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
cli-source = "revanced/revanced-cli"
build-mode = "module"
arch = "arm64-v8a"
riplib = false

[GooglePhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
cli-source = "revanced/revanced-cli"
build-mode = "module"
arch = "arm64-v8a"
riplib = false

[Cricbuzz]
apkmirror-dlurl = "https://www.apkmirror.com/apk/cricbuzz-com/cricbuzz-live-cricket-scores-news/"
uptodown-dlurl = "https://cricbuzz-cricket-scores-and-news.en.uptodown.com/android"
cli-source = "revanced/revanced-cli"
riplib = false

[InfinityPlus]
apkmirror-dlurl = "https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit-plus/"
archive-dlurl = "https://archive.org/download/moreorlessanand-apks/ml.docilealligator.infinityforreddit.plus/"
cli-source = "revanced/revanced-cli"
patcher-args = "-Oclient-id=v17_APk4YnTwWyhTs9xV0Q "
included-patches = "'Spoof client'"
riplib = false

[inshorts]
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2/"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
cli-source = "revanced/revanced-cli"
arch = "arm64-v8a"
riplib = false

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
cli-source = "revanced/revanced-cli"
riplib = false
